name: Rockbox build
on:
  workflow_dispatch:
    inputs:
      upload_debug:
        description: 'Upload debug files'
        required: false
        type: boolean
        default: false
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: xDuoo X3II
            arch: y
            platform: 242
            type: AL

    runs-on: ubuntu-latest
    container: ${{matrix.container}} 
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v7

    - name: Prepare container
      if: matrix.container != null
      run: |
        apt-get update
        apt-get install -y sudo

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y automake bison build-essential ccache flex libc6-dev libgmp3-dev libmpfr-dev \
        libsdl1.2-dev libtool-bin texinfo zip gawk wget libmpc-dev gettext gtk-doc-tools
        
    - name: root suid tar
      # workaround for caching system files
      run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

    - name: Restore toolchain dependencies
      id: cache-before
      uses: actions/cache/restore@v6
      with:
        path: |
          /tmp/local
        key: ${{ runner.os }}-toolchain-${{ matrix.arch }}-${{ hashFiles('tools/rockboxdev.sh') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-${{ matrix.arch }}-
          ${{ runner.os }}-toolchain-

    - name: Run rockboxdev.sh
      if: steps.cache-before.outputs.cache-hit != 'true'
      run: |
        cd tools
        chmod +x rockboxdev.sh
        sudo ./rockboxdev.sh --target=${{matrix.arch}} --prefix=/tmp/local

    - name: Cache toolchain dependencies
      if: steps.cache-before.outputs.cache-hit != 'true'
      uses: actions/cache@v6
      with:
        path: |
          /tmp/local
        key: ${{ runner.os }}-toolchain-${{ matrix.arch }}-${{ hashFiles('tools/rockboxdev.sh') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-${{ matrix.arch }}-

    - name: Add /tmp/local/bin to PATH
      run: |
        echo "/tmp/local/bin" >> $GITHUB_PATH

    - name: Build Rockbox
      run: |
        mkdir build
        cd build
        ../tools/configure --with-stack-protector=strong --target=${{matrix.platform}} --type=${{matrix.type || 'N'}}
        make -j
        make zip

    - name: Upload build
      uses: actions/upload-artifact@v7
      if: matrix.type != 'B'
      with:
        name: ${{matrix.name}}.zip
        path: build/rockbox.zip

    - name: Upload bootloader
      uses: actions/upload-artifact@v7
      if: matrix.type == 'B'
      with:
        name: ${{matrix.name}}.zip
        path: build/bootloader*

    - name: Upload debug files
      uses: actions/upload-artifact@v7
      with:
        name: ${{matrix.name}}-debug
        path: |
          build/**/*.elf
          build/**/*.map
          build/**/*.log
          build/**/*.dmp
          build/**/*.dump

    - name: Upload log
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: ${{matrix.name}}Logs
        path: /tmp/rbdev-build/*.log
