name: Rockbox build
on: [workflow_dispatch, push, pull_request]
 
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Rocker
            # Other arch targets https://github.com/bahusoid/rockbox/blob/992dfe0118f367533fe23170b1459c2818a629a1/tools/rockboxdev.sh#L697-L701
            arch: y
            # Other platform targets https://github.com/Rockbox/rockbox/blob/dd1fbd51fc7bb3fa7237b3bc34335e99bef29e35/tools/configure#L1560-L1615
            platform: 240

          - name: xDuoo X3II
            arch: y
            platform: 242

          - name: Samsung YP-R0
            arch: x
            platform: samsungypr0
            container: ubuntu:22.04

          - name: clipZip
            arch: a
            platform: 65

          - name: mRobe500
            arch: a
            platform: 70

          - name: IriverH300
            arch: m
            platform: 11

          - name: iriverh120_rtcmod
            arch: m
            platform: 10
            type: AR

          - name: ipod mini 2g
            arch: a
            platform: 26
            type: AR

          - name: Hiby R1
            arch: y
            platform: hibyr1

          - name: Hiby R1 bootloader
            arch: y
            platform: hibyr1
            type: B
          
          - name: Hiby R3 PRO II
            arch: y
            platform: hibyr3proii

          - name: Hiby R3 PRO II bootloader
            arch: y
            platform: hibyr3proii
            type: B

          - name: Sansa E200v2
            arch: a
            platform: sansae200v2

          - name: AIGO EROS Q (Native)
            arch: i
            platform: erosqnative

    runs-on: ubuntu-latest
    container: ${{matrix.container}} 
    name: ${{matrix.name}}

    steps:
    - uses: actions/checkout@v7

    - name: Prepare container
      if: matrix.container != null
      run: |
        apt-get update
        apt-get install -y sudo

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y automake bison build-essential ccache flex libc6-dev libgmp3-dev libmpfr-dev \
        libsdl1.2-dev libtool-bin texinfo zip gawk wget libmpc-dev gettext gtk-doc-tools
        
    - name: root suid tar
      # workaround for caching system files
      run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

    - name: Restore toolchain dependencies
      id: cache-before
      uses: actions/cache/restore@v6
      with:
        path: |
          /tmp/local
        key: ${{ runner.os }}-toolchain-${{ matrix.arch }}-${{ hashFiles('tools/rockboxdev.sh') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-${{ matrix.arch }}-
          ${{ runner.os }}-toolchain-

    - name: Run rockboxdev.sh
      if: steps.cache-before.outputs.cache-hit != 'true'
      run: |
        cd tools
        chmod +x rockboxdev.sh
        sudo ./rockboxdev.sh --target=${{matrix.arch}} --prefix=/tmp/local

    - name: Cache toolchain dependencies
      if: steps.cache-before.outputs.cache-hit != 'true'
      uses: actions/cache@v6
      with:
        path: |
          /tmp/local
        key: ${{ runner.os }}-toolchain-${{ matrix.arch }}-${{ hashFiles('tools/rockboxdev.sh') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-${{ matrix.arch }}-

    - name: Add /tmp/local/bin to PATH
      run: |
        echo "/tmp/local/bin" >> $GITHUB_PATH

    - name: Build Rockbox
      run: |
        mkdir build
        cd build
        ../tools/configure --target=${{matrix.platform}} --type=${{matrix.type || 'N'}}
        make -j
        make zip

    - name: Upload build
      uses: actions/upload-artifact@v7
      if: matrix.type != 'B'
      with:
        name: ${{matrix.name}}.zip
        path: build/rockbox.zip

    - name: Upload bootloader
      uses: actions/upload-artifact@v7
      if: matrix.type == 'B'
      with:
        name: ${{matrix.name}}.zip
        path: build/bootloader*

    - name: Upload debug files
      uses: actions/upload-artifact@v7
      with:
        name: ${{matrix.name}}-debug
        path: |
          build/**/*.elf
          build/**/*.map
          build/**/*.log
          build/**/*.dmp
          build/**/*.dump

    - name: Upload log
      uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: ${{matrix.name}}Logs
        path: /tmp/rbdev-build/*.log
