name: Clip Zip build
on: [workflow_dispatch, push, pull_request]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: make it all
      run: |
        sudo apt-get install automake bison build-essential ccache flex libc6-dev libgmp3-dev libmpfr-dev libsdl1.2-dev libtool-bin texinfo zip gawk wget libmpc-dev gettext
        cd tools
        chmod +x rockboxdev.sh
        # Other targets https://github.com/bahusoid/rockbox/blob/992dfe0118f367533fe23170b1459c2818a629a1/tools/rockboxdev.sh#L697-L701
        sudo ./rockboxdev.sh --target=a
        cd ..
        mkdir clipZip
        cd clipZip
        # Other targets https://github.com/Rockbox/rockbox/blob/dd1fbd51fc7bb3fa7237b3bc34335e99bef29e35/tools/configure#L1560-L1615
        ../tools/configure --target=65 --type=N
        make -j
        make zip
      
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: rockbox.zip
        path: clipZip/rockbox.zip
    
    - name: Upload log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: logs
        path: /tmp/rbdev-build/*.log